FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Presentation/CleanArchitectureWebApi/CleanArchitectureWebApi.csproj", "Presentation/CleanArchitectureWebApi/"]
RUN dotnet restore "Presentation/CleanArchitectureWebApi/CleanArchitectureWebApi.csproj"
COPY . .
WORKDIR "/src/Presentation/CleanArchitectureWebApi"
RUN dotnet build "CleanArchitectureWebApi.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "CleanArchitectureWebApi.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CleanArchitectureWebApi.dll"]
